apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: learningcenter-policy-app
  namespace: $SESSION_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:$SESSION_NAMESPACE
