#@ load("@ytt:data", "data")
---
apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tap-development
spec:
  title: Experimental
  description: Pre-release development version of the TAP Demo
  vendor: vmware.com
  difficulty: beginner
  duration: 60m
  url: https://github.com/tanzu-end-to-end/tap-workshop
  content:
    image: #@ "harbor.{}/tanzu-e2e/eduk8s-tap-workshop:latest".format(data.values.ingress.domain)
    files: #@ "github.com/{}/tap-workshop?ref=development".format(data.values.git.account)
  session:
    resources:
      memory: 3Gi
    env:
      - name: GITEA_PASSWORD
        value: #@ data.values.gitea.adminPassword
      - name: VIEW_CLUSTER_DOMAIN
        value: #@ data.values.tap.view_cluster_domain
      - name: KUBE_CONFIG
        value: #@ data.values.tap.kubeconfig
      - name: HARBOR_USER
        value: #@ data.values.harbor.user
      - name: HARBOR_PASSWORD
        value: #@ data.values.harbor.adminPassword
    namespaces:
      budget: custom
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      registry:
        enabled: true
    objects:
      - apiVersion: v1
        kind: LimitRange
        metadata:
          name: resource-limits
        spec:
          limits:
            - type: PersistentVolumeClaim
              max:
                storage: 10Gi
