apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: TrainingPortal
metadata:
  name: tap-demos
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    credentials:
      admin:
        username: admin
        password: VMware1!
    title: Tanzu Application Platform Demos
    registration:
      type: one-step
      enabled: false
    updates:
      workshop: true
    sessions:
      maximum: 10
  workshops:
    - name: tap-overview
      expires: 240h
      orphaned: 240h
      capacity: 2
      reserved: 1
      #    - name: tap-development
      #expires: 60m
      #orphaned: 20m
      #capacity: 10
      #reserved: 0
